function get-RandomPassword {
    param (
        [int]$length = 10
    )
    $password = (-join ((0x30..0x39) + (0x41..0x5A) + (0x61..0x7A) | Get-Random -Count $length | ForEach-Object { [char]$_ })) + 'R2-D2!'
    return $password
}
function new-localusers {
    param (
        [array]$usersToCreateArray
    )
    foreach ($username in $usersToCreateArray) {
        # genereer random wachtwoord. 
        $randomGeneratedPassword = get-RandomPassword

        #convert hem naar een secure string
        $passwordSecured = ConvertTo-SecureString $randomGeneratedPassword -AsPlainText -Force

        #maak newuser aan
        New-LocalUser -Name $username -Password $passwordSecured -Description "generated by powershellscript"
        Write-Output "User '$username' has been created with the password: $password"
    }
}
function Add-UserToAdministratorsGroup {
    param (
        [array]$inputarray
    )
    $usersToCreateArray | ForEach-Object{
        Add-LocalGroupMember -Group "Administrators" -Member $_
        Write-Output "User '$_' has been added to the Administrators group."
    }   
}


# Main script logic
$usersToCreate = "firstUser", "SecondUser", "ThirdUser"
new-localusers -usersToCreateArray $usersToCreate
Add-UserToAdministratorsGroup -inputarray $usersToCreate